# Generated by Django 5.1.4 on 2024-12-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20241231_1418"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicmonster",
            name="charisma_mod",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="basicmonster",
            name="constitution_mod",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="basicmonster",
            name="dexterity_mod",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="basicmonster",
            name="intelligence_mod",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="basicmonster",
            name="strength_mod",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="basicmonster",
            name="wisdom_mod",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
