# Generated by Django 5.1.4 on 2024-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_charactersheet_alignment_charactersheet_armor_class_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="charactersheet",
            old_name="backstory",
            new_name="conditions",
        ),
        migrations.RenameField(
            model_name="charactersheet",
            old_name="equipment",
            new_name="reactions",
        ),
        migrations.RenameField(
            model_name="charactersheet",
            old_name="items",
            new_name="special_abilities",
        ),
        migrations.RenameField(
            model_name="charactersheet",
            old_name="notes",
            new_name="spells_known",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="proficiency_acrobatics",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="proficiency_arcana",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="proficiency_history",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="proficiency_perception",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="proficiency_persuasion",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="proficiency_stealth",
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="attack_priority",
            field=models.CharField(default="Lowest HP", max_length=50),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="available_actions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="bonus_actions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="combat_role",
            field=models.CharField(default="Fighter", max_length=50),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="escape_threshold",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="ongoing_damage",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="preferred_range",
            field=models.CharField(default="Melee", max_length=20),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="primary_attack_bonus",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="primary_attack_damage",
            field=models.CharField(default="1d8+0", max_length=20),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="primary_attack_damage_type",
            field=models.CharField(default="Bludgeoning", max_length=20),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="primary_attack_name",
            field=models.CharField(default="Unarmed Strike", max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="primary_attack_type",
            field=models.CharField(
                choices=[("Melee", "Melee"), ("Ranged", "Ranged")],
                default="Melee",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="secondary_attack_bonus",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="secondary_attack_damage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="secondary_attack_damage_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="secondary_attack_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="secondary_attack_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="temporary_hit_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
