# Generated by Django 5.1.4 on 2024-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_backstory_charactersheet_conditions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="alignment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="armor_class",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="attack_priority",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="available_actions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="bonus_actions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="charisma",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="class_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="combat_role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="conditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="constitution",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="dexterity",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="escape_threshold",
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="hit_points",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="initiative",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="intelligence",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="level",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="ongoing_damage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="preferred_range",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="primary_attack_bonus",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="primary_attack_damage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="primary_attack_damage_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="primary_attack_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="primary_attack_type",
            field=models.CharField(
                blank=True,
                choices=[("Melee", "Melee"), ("Ranged", "Ranged")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="race",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="reactions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="special_abilities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="speed",
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="spell_slots",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="spells_known",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="strength",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="temporary_hit_points",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="wisdom",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
