# Generated by Django 5.1.4 on 2024-12-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_charactersheet_finished_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("alignment", models.CharField(blank=True, max_length=50, null=True)),
                ("armor_class", models.IntegerField(blank=True, null=True)),
                ("hit_points", models.IntegerField(blank=True, null=True)),
                ("speed", models.CharField(blank=True, max_length=100, null=True)),
                ("strength", models.IntegerField(blank=True, null=True)),
                ("dexterity", models.IntegerField(blank=True, null=True)),
                ("constitution", models.IntegerField(blank=True, null=True)),
                ("intelligence", models.IntegerField(blank=True, null=True)),
                ("wisdom", models.IntegerField(blank=True, null=True)),
                ("charisma", models.IntegerField(blank=True, null=True)),
                ("saving_throws", models.TextField(blank=True, null=True)),
                ("damage_resistances", models.TextField(blank=True, null=True)),
                ("damage_immunities", models.TextField(blank=True, null=True)),
                ("condition_immunities", models.TextField(blank=True, null=True)),
                ("senses", models.TextField(blank=True, null=True)),
                ("languages", models.TextField(blank=True, null=True)),
                (
                    "challenge_rating",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("abilities", models.TextField(blank=True, null=True)),
                ("actions", models.TextField(blank=True, null=True)),
                ("reactions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="finished",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
